name: checksprecommits

on:
  precommit:
    branches: [master]

jobs:
  precommitchecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instalar precommit
        run: pip install pre-commit
      - name: Correr precommit checks
        run: pre-commit run --all-files
