name: Precommit checks

on:
  pre-commit:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instalar pre-commit
        run: pip install pre-commit
      - name: Correr pre-commit checks
        run: pre-commit run --all-files
